name: Image Scan
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image name including tag, e.g. alpine:3.18.2'
        required: true 
        type: string
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image: ${{ github.event.inputs.image }}
    steps:
      - uses: actions/checkout@v3
      - name: Set the value
        run: |
          echo "image_name=$(echo ${{ env.image }} | cut -d ":" -f 1 )" >> $GITHUB_ENV
          echo "image_tag=$(echo ${{ env.image }} | cut -d ":" -f 2 )" >> $GITHUB_ENV
      - run: mkdir -p ${{ env.image_name }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.event.inputs.image }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          output: '${{ env.image_name }}/${{ env.image_tag }}_report'
    
      - name: Push to security/${{ env.image_name }}/${{ env.image_tag }}
        run: |
          git config --global user.email "Workflow@github.com"
          git config --global user.name "Auto-Workflow"
          git checkout -b security/${{ env.image_name }}/${{ env.image_tag }}
          git add ${{ env.image_name }}/${{ env.image_tag }}_report
          git commit -m '[Workflow] Add ${{ github.event.inputs.image }} security report'
          git push origin security/${{ env.image_name }}/${{ env.image_tag }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@@v5.0.2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: workflow
          base: security/${{ env.image_name }}/${{ env.image_tag }}
          delete-branch: false
          title: 'Add ${{ github.event.inputs.image }} security report'
          body: |
            Add ${{ github.event.inputs.image }} security report
            - see file `${{ env.image_name }}/${{ env.image_tag }}_report`
          labels: |
            ${{ env.image_name }}
          reviewers: dannymonkey
          draft: true